; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
data_dir = tools/configurator/web

[env:waveshare_esp32s3_touch_lcd_128]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
upload_protocol = esptool
upload_port = COM7
monitor_speed = 115200
monitor_port = COM7
board_build.partitions = large_spiffs_16MB.csv
board_build.filesystem = littlefs
build_src_filter =
	+<*>
	-<original/>
build_flags = 
	-D BOARD_HAS_PSRAM
lib_deps = 
	handmade0octopus/ESP32-TWAI-CAN@^1.0.1
	baracodadailyhealthtech/cJSON@^1.7.18
	bblanchon/ArduinoJson@^7.0.4
	;h2zero/NimBLE-Arduino@^1.4.1
